version: "3"

services:
  e2e:
    build: ./e2e
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    depends_on:
      - app
    command: bash -c "npm run cache && tail -f /e2e/cypress/logs/cypress.log"
  app:
    build:
      context: ./app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment: 
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on: 
      - db
  db:
    image: postgres:10-alpine
    environment: 
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword